// Theme Definitions
const themes = {
        cyber: {
          name: 'Cyber',
          bgPrimary: 'bg-[#011627]',
          gradientFrom: 'from-teal-400',
          gradientVia: 'via-cyan-400',
          gradientTo: 'to-emerald-400',
          accentLight: 'teal-400',
          accentMid: 'cyan-400',
          accentDark: 'emerald-400',
        },
        aurora: {
          name: 'Aurora',
          bgPrimary: 'bg-[#0F172A]',
          gradientFrom: 'from-purple-400',
          gradientVia: 'via-pink-400',
          gradientTo: 'to-orange-400',
          accentLight: 'purple-400',
          accentMid: 'pink-400',
          accentDark: 'orange-400',
        },
        matrix: {
          name: 'Matrix',
          bgPrimary: 'bg-[#0A0F0D]',
          gradientFrom: 'from-green-400',
          gradientVia: 'via-emerald-400',
          gradientTo: 'to-lime-400',
          accentLight: 'green-400',
          accentMid: 'emerald-400',
          accentDark: 'lime-400',
        },
        quantum: {
          name: 'Quantum',
          bgPrimary: 'bg-[#0D1117]',
          gradientFrom: 'from-violet-400',
          gradientVia: 'via-indigo-400',
          gradientTo: 'to-blue-400',
          accentLight: 'violet-400',
          accentMid: 'indigo-400',
          accentDark: 'blue-400',
        },
        sunset: {
          name: 'Sunset',
          bgPrimary: 'bg-[#1A1423]',
          gradientFrom: 'from-red-400',
          gradientVia: 'via-orange-400',
          gradientTo: 'to-yellow-400',
          accentLight: 'red-400',
          accentMid: 'orange-400',
          accentDark: 'yellow-400',
        },
        neon: {
          name: 'Neon',
          bgPrimary: 'bg-[#120E43]',
          gradientFrom: 'from-pink-500',
          gradientVia: 'via-purple-500',
          gradientTo: 'to-blue-500',
          accentLight: 'pink-500',
          accentMid: 'purple-500',
          accentDark: 'blue-500',
        },
        pastel: {
          name: 'Pastel',
          bgPrimary: 'bg-[#F8F1F1]',
          gradientFrom: 'from-pink-200',
          gradientVia: 'via-yellow-200',
          gradientTo: 'to-green-200',
          accentLight: 'pink-200',
          accentMid: 'yellow-200',
          accentDark: 'green-200',
        },
        galaxy: {
          name: 'Galaxy',
          bgPrimary: 'bg-[#1C1E33]',
          gradientFrom: 'from-indigo-600',
          gradientVia: 'via-purple-600',
          gradientTo: 'to-black',
          accentLight: 'indigo-600',
          accentMid: 'purple-600',
          accentDark: 'black',
        },
        tropical: {
          name: 'Tropical',
          bgPrimary: 'bg-[#1B4332]',
          gradientFrom: 'from-lime-400',
          gradientVia: 'via-yellow-400',
          gradientTo: 'to-teal-400',
          accentLight: 'lime-400',
          accentMid: 'yellow-400',
          accentDark: 'teal-400',
        },
        dawn: {
          name: 'Dawn',
          bgPrimary: 'bg-[#EAE2B7]',
          gradientFrom: 'from-pink-300',
          gradientVia: 'via-orange-300',
          gradientTo: 'to-yellow-300',
          accentLight: 'pink-300',
          accentMid: 'orange-300',
          accentDark: 'yellow-300',
        },
        solarized: {
          name: 'Solarized',
          bgPrimary: 'bg-[#002B36]',
          gradientFrom: 'from-yellow-500',
          gradientVia: 'via-orange-500',
          gradientTo: 'to-red-500',
          accentLight: 'yellow-500',
          accentMid: 'orange-500',
          accentDark: 'red-500',
        },
        ocean: {
          name: 'Ocean',
          bgPrimary: 'bg-[#0E3B43]',
          gradientFrom: 'from-cyan-500',
          gradientVia: 'via-blue-500',
          gradientTo: 'to-indigo-500',
          accentLight: 'cyan-500',
          accentMid: 'blue-500',
          accentDark: 'indigo-500',
        },
        forest: {
          name: 'Forest',
          bgPrimary: 'bg-[#003E29]',
          gradientFrom: 'from-green-500',
          gradientVia: 'via-teal-500',
          gradientTo: 'to-emerald-500',
          accentLight: 'green-500',
          accentMid: 'teal-500',
          accentDark: 'emerald-500',
        },
        magma: {
          name: 'Magma',
          bgPrimary: 'bg-[#2B0B0B]',
          gradientFrom: 'from-red-600',
          gradientVia: 'via-orange-600',
          gradientTo: 'to-yellow-600',
          accentLight: 'red-600',
          accentMid: 'orange-600',
          accentDark: 'yellow-600',
        }
      };
      
  export default themes;
  