export const themes: Record<string, DesignTheme> = {
  cyber: {
    id: 'cyber',
    name: 'Cyber',
    bgPrimary: 'bg-gray-900',
    accent: {
      light: 'text-teal-300',
      DEFAULT: 'text-teal-400',
      dark: 'text-teal-500',
    },
    text: {
      primary: 'text-gray-50',
      secondary: 'text-gray-400',
      tertiary: 'text-gray-500',
      accent: 'text-teal-400',
      error: 'text-red-400',
      success: 'text-green-400',
      warning: 'text-yellow-400',
    },
    surfaces: {
      primary: 'bg-gray-900',
      secondary: 'bg-gray-800',
      tertiary: 'bg-gray-700',
      elevated: 'bg-gray-800',
      interactive: 'bg-gray-700',
      hover: 'bg-gray-600',
      active: 'bg-gray-500',
    },
    border: {
      color: 'border-gray-700',
      hover: 'border-gray-600',
      active: 'border-gray-500',
      width: 'border',
      radius: 'rounded-lg',
    },
    gradient: {
      enabled: true,
      from: 'from-teal-400',
      to: 'to-blue-500',
      direction: 'to-r',
    },
    shadow: {
      sm: 'shadow-sm',
      DEFAULT: 'shadow',
      lg: 'shadow-lg',
      focus: 'ring-2 ring-teal-500/50',
    },
    states: {
      hover: 'hover:bg-gray-700',
      focus: 'focus:ring-2 focus:ring-teal-500/50',
      active: 'active:bg-gray-600',
      disabled: 'opacity-50 cursor-not-allowed',
    },
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    bgPrimary: 'bg-white',
    accent: {
      light: 'text-blue-300',
      DEFAULT: 'text-blue-500',
      dark: 'text-blue-700',
    },
    text: {
      primary: 'text-gray-900',
      secondary: 'text-gray-600',
      tertiary: 'text-gray-400',
      accent: 'text-blue-500',
      error: 'text-red-500',
      success: 'text-green-500',
      warning: 'text-yellow-500',
    },
    surfaces: {
      primary: 'bg-white',
      secondary: 'bg-gray-50',
      tertiary: 'bg-gray-100',
      elevated: 'bg-white',
      interactive: 'bg-gray-50',
      hover: 'bg-gray-100',
      active: 'bg-gray-200',
    },
    border: {
      color: 'border-gray-200',
      hover: 'border-gray-300',
      active: 'border-gray-400',
      width: 'border',
      radius: 'rounded-lg',
    },
    shadow: {
      sm: 'shadow-sm',
      DEFAULT: 'shadow',
      lg: 'shadow-lg',
      focus: 'ring-2 ring-blue-500/50',
    },
    states: {
      hover: 'hover:bg-gray-50',
      focus: 'focus:ring-2 focus:ring-blue-500/50',
      active: 'active:bg-gray-100',
      disabled: 'opacity-50 cursor-not-allowed',
    },
  },
  dark: {
    id: 'dark',
    name: 'Dark',
    bgPrimary: 'bg-black',
    accent: {
      light: 'text-purple-300',
      DEFAULT: 'text-purple-500',
      dark: 'text-purple-700',
    },
    text: {
      primary: 'text-white',
      secondary: 'text-gray-400',
      tertiary: 'text-gray-600',
      accent: 'text-purple-500',
      error: 'text-red-500',
      success: 'text-green-500',
      warning: 'text-yellow-500',
    },
    surfaces: {
      primary: 'bg-black',
      secondary: 'bg-gray-800',
      tertiary: 'bg-gray-700',
      elevated: 'bg-gray-800',
      interactive: 'bg-gray-700',
      hover: 'bg-gray-600',
      active: 'bg-gray-500',
    },
    border: {
      color: 'border-gray-600',
      hover: 'border-gray-500',
      active: 'border-gray-400',
      width: 'border',
      radius: 'rounded-md',
    },
    shadow: {
      sm: 'shadow-sm',
      DEFAULT: 'shadow',
      lg: 'shadow-lg',
      focus: 'ring-2 ring-purple-500/50',
    },
    states: {
      hover: 'hover:bg-gray-800',
      focus: 'focus:ring-2 focus:ring-purple-500/50',
      active: 'active:bg-gray-700',
      disabled: 'opacity-40 cursor-not-allowed',
    },
  },
  retro: {
    id: 'retro',
    name: 'Retro',
    bgPrimary: 'bg-yellow-50',
    accent: {
      light: 'text-orange-300',
      DEFAULT: 'text-orange-500',
      dark: 'text-orange-700',
    },
    text: {
      primary: 'text-gray-900',
      secondary: 'text-gray-700',
      tertiary: 'text-gray-500',
      accent: 'text-orange-500',
      error: 'text-red-600',
      success: 'text-green-600',
      warning: 'text-yellow-600',
    },
    surfaces: {
      primary: 'bg-yellow-50',
      secondary: 'bg-yellow-100',
      tertiary: 'bg-yellow-200',
      elevated: 'bg-yellow-50',
      interactive: 'bg-yellow-100',
      hover: 'bg-yellow-200',
      active: 'bg-yellow-300',
    },
    border: {
      color: 'border-yellow-300',
      hover: 'border-yellow-400',
      active: 'border-yellow-500',
      width: 'border',
      radius: 'rounded-lg',
    },
    shadow: {
      sm: 'shadow-sm',
      DEFAULT: 'shadow-md',
      lg: 'shadow-lg',
      focus: 'ring-2 ring-orange-500/50',
    },
    states: {
      hover: 'hover:bg-yellow-200',
      focus: 'focus:ring-2 focus:ring-orange-500/50',
      active: 'active:bg-yellow-300',
      disabled: 'opacity-50 cursor-not-allowed',
    },
  },
  pastel: {
    id: 'pastel',
    name: 'Pastel',
    bgPrimary: 'bg-pink-50',
    accent: {
      light: 'text-pink-300',
      DEFAULT: 'text-pink-500',
      dark: 'text-pink-700',
    },
    text: {
      primary: 'text-gray-800',
      secondary: 'text-gray-600',
      tertiary: 'text-gray-400',
      accent: 'text-pink-500',
      error: 'text-red-500',
      success: 'text-green-500',
      warning: 'text-yellow-500',
    },
    surfaces: {
      primary: 'bg-pink-50',
      secondary: 'bg-pink-100',
      tertiary: 'bg-pink-200',
      elevated: 'bg-pink-100',
      interactive: 'bg-pink-200',
      hover: 'bg-pink-300',
      active: 'bg-pink-400',
    },
    border: {
      color: 'border-pink-300',
      hover: 'border-pink-400',
      active: 'border-pink-500',
      width: 'border',
      radius: 'rounded-full',
    },
    shadow: {
      sm: 'shadow-sm',
      DEFAULT: 'shadow',
      lg: 'shadow-lg',
      focus: 'ring-2 ring-pink-500/50',
    },
    states: {
      hover: 'hover:bg-pink-200',
      focus: 'focus:ring-2 focus:ring-pink-500/50',
      active: 'active:bg-pink-300',
      disabled: 'opacity-50 cursor-not-allowed',
    },
  },
};
